name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.API_TOKEN_GITHUB }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: |
          IMAGE_PLATFORM="${IMAGE_PLATFORM:-linux/amd64}"
          docker buildx build \
          --platform $IMAGE_PLATFORM \
          --build-arg IMAGE_PLATFORM=$IMAGE_PLATFORM \
          --file ./docker/php/Dockerfile \
          --tag ghcr.io/axyr/hue-waste-bin-alerter:latest \
          --tag ghcr.io/axyr/hue-waste-bin-alerter:${GIT_BRANCH}-${GIT_SHA:0:7}-$(date +%s) \
          --push .
